PD-826 download url only response added in download methods
appknox/googleplay-api pull request #2
Opened 2023-04-25 11:56 UTC by mrasif

* `link_only` filter added in download method.
* This changes required to get download url only, without having file content in response,
  So, download process can be done later.

2023-04-25 12:49 UTC, sureshdsk commented on gpapi/googleplay.py
> +            if link_only:
this download method works in multiple ways.
1. single apk - which you've implemented
2. split apk files - multiple apk links will be there - missing
3. additional obb file links also there - missing - not sure of its use at the moment. 

so i feel its better to create a new method and do this.

2023-04-25 12:49 UTC, sureshdsk requested changes
need changes.

2023-04-26 12:34 UTC, mrasif commented on gpapi/googleplay.py
> +            if link_only:
Added specific method for extracting download link

2023-09-25 13:17 UTC, subho007 commented
Closing this PR since it is irrelevant now

2023-09-25 13:17 UTC, closed without merging